steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-f'
      - 'Dockerfile'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/medisupply/order-query-api'
      - '.'
images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/medisupply/order-query-api'