---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: default
type: Opaque
stringData:
  postgres-root-username: <username>
  postgres-root-password: <password>
  postgres-host: <host>
  postgres-port: <port>
  postgres-db: <db-name>

---
apiVersion: v1
kind: Secret
metadata:
  name: google-cloud-secret
  namespace: default
type: Opaque
stringData:
  google-cloud-project-id: <project-id>
  pubsub-topic-name-proveedores: proveedores-events
  google-maps-api-key: <google-maps-api-key>
  google-api-key: <google-api-key>
  smtp-host: <smtp-host>
  smtp-port: <smtp-port>
  smtp-user: <smtp-user>
  smtp-password: <smtp-password>
  smtp-from: <smtp-from>
  pubsub-topic-name-ventas: ventas-events
  pubsub-topic-name-clientes: clientes-events
  pubsub-topic-name-productos: productos-events
  pubsub-topic-name-auditoria: auditoria-events
  pubsub-topic-name-logistica: logistica-events
  pubsub-topic-name-autenticacion: autenticacion-events
  pubsub-topic-name-reportes: reportes-events
  pubsub-topic-name-inventario: inventario-events
  pubsub-topic-name-ordenes-command-api: create-order-command
  pubsub-topic-name-ordenes-command-handler: order-created
  pubsub-topic-name-ordenes-query-projection: order-projection-created
  pubsub-topic-name-visitas: visitas-events