apiVersion: apps/v1
kind: Deployment
metadata:
  name: productos-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: productos-service
  template:
    metadata:
      labels:
        app: productos-service
    spec:
      containers:
        - name: productos-container
          image: us-central1-docker.pkg.dev/medisupply-474421/medisupply/productos:latest
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8000
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-root-username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-root-password
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-host
            - name: POSTGRES_PORT
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-port
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-db
            - name: PYTHONUNBUFFERED
              value: "1"
            - name: REDIS_HOST
              value: "redis-service"
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_DB
              value: "0"
            - name: GOOGLE_CLOUD_PROJECT_ID
              valueFrom:
                secretKeyRef:
                  name: google-cloud-secret
                  key: google-cloud-project-id
            - name: PUBSUB_TOPIC_NAME
              valueFrom:
                secretKeyRef:
                  name: google-cloud-secret
                  key: pubsub-topic-name-productos
            - name: PROVEEDORES_SERVICE_URL
              value: "http://proveedores-service"
---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: productos-backend-config
spec:
  healthCheck:
    checkIntervalSec: 30
    timeoutSec: 5
    requestPath: "/health"
    type: HTTP
    port: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: productos-service
  namespace: default
  annotations:
    cloud.google.com/backend-config: '{"default": "productos-backend-config"}'
spec:
  type: NodePort
  selector:
    app: productos-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30004
